version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-service
    working_dir: /var/www/${PATH_NAME:-php-telegram-bot}
    volumes:
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/${PATH_NAME:-php-telegram-bot}
    ports:
    - ${HTTP_PORT:-8089}:80
    links:
      - php-fpm
  php-fpm:
    image: php:8.0.11-fpm-alpine
    container_name: fpm-service
    volumes:
    - ./:/var/www/${PATH_NAME:-php-telegram-bot}
  composer:
    image: composer/composer
    container_name: composer-service
    working_dir: /var/www/${PATH_NAME:-php-telegram-bot}
    volumes:
    - ./:/var/www/${PATH_NAME:-php-telegram-bot}
    command: install
    links:
      - php-fpm